// Flat C exports observed in dwmapi.dll. Unknown ABIs are intentionally not declared.
// Validated dialects: ISO C17/C23/C26 draft and Windissect C20 (C ABI under C++20).
#pragma once
#ifndef DWMAPI_C_H
#define DWMAPI_C_H
#if defined(__cplusplus)
#  if __cplusplus < 202002L
#    define WINDISSECT_C20_PROFILE 0
#  else
#    define WINDISSECT_C20_PROFILE 1
#  endif
extern "C" {
#else
#  if defined(__STDC_VERSION__) && __STDC_VERSION__ < 201710L
#    error "Windissect C output requires C17 or newer"
#  endif
#  define WINDISSECT_C20_PROFILE 0
#  define WINDISSECT_C_STANDARD __STDC_VERSION__
#endif

// Export: #ordinal170 (ABI unverified)
// Export: DwmpCreateSessionShutdownEvent (ABI unverified)
// Export: DwmSetIconicThumbnail (ABI unverified)
// Export: DwmpAllocateSecurityDescriptor (ABI unverified)
// Export: DwmpSetColorizationParameters (ABI unverified)
// Export: #ordinal159 (ABI unverified)
// Export: DwmpUpdateAccentBlurRect (ABI unverified)
// Export: DwmIsCompositionEnabled (ABI unverified)
// Export: DwmGetCompositionTimingInfo (ABI unverified)
// Export: #ordinal132 (ABI unverified)
// Export: DwmpGetCompositionTimingInfoEx (ABI unverified)
// Export: DwmShowContact (ABI unverified)
// Export: DwmUnregisterThumbnail (ABI unverified)
// Export: DwmExtendFrameIntoClientArea (ABI unverified)
// Export: #ordinal162 (ABI unverified)
// Export: DwmpQueryWindowThumbnailSourceSize (ABI unverified)
// Export: DwmDefWindowProc (ABI unverified)
// Export: DwmpDxGetWindowSharedSurface (ABI unverified)
// Export: DwmFlush (ABI unverified)
// Export: DwmSetWindowAttribute (ABI unverified)
// Export: DwmGetWindowAttribute (ABI unverified)
// Export: DwmpGetColorizationParameters (ABI unverified)
// Export: #ordinal169 (ABI unverified)
// Export: DwmpReadColorizationParameters (ABI unverified)
// Export: #ordinal147 (ABI unverified)
// Export: DwmpCreateSharedThumbnailVisual (ABI unverified)
// Export: DwmGetColorizationColor (ABI unverified)
// Export: DwmUpdateThumbnailProperties (ABI unverified)
// Export: #ordinal163 (ABI unverified)
// Export: DwmpCreateSharedMultiWindowVisual (ABI unverified)
// Export: DwmInvalidateIconicBitmaps (ABI unverified)
// Export: DwmpDxgiIsThreadDesktopComposited (ABI unverified)
// Export: #ordinal186 (ABI unverified)
// Export: DwmpSetBlurredWallpaperSurface (ABI unverified)
// Export: DwmQueryThumbnailSourceSize (ABI unverified)
// Export: #ordinal114 (ABI unverified)
// Export: DwmpQueryThumbnailType (ABI unverified)
// Export: #ordinal113 (ABI unverified)
// Export: DwmpActivateLivePreview (ABI unverified)
// Export: #ordinal187 (ABI unverified)
// Export: DwmpActivateLivePreviewEx (ABI unverified)
// Export: #ordinal139 (ABI unverified)
// Export: DwmpTransitionWindow (ABI unverified)
// Export: #ordinal141 (ABI unverified)
// Export: DwmpTransitionWindowWithRects (ABI unverified)
// Export: #ordinal179 (ABI unverified)
// Export: DwmpGetTitlebarInfo (ABI unverified)
// Export: #ordinal104 (ABI unverified)
// Export: #ordinal108 (ABI unverified)
// Export: #ordinal175 (ABI unverified)
// Export: #ordinal198 (ABI unverified)
// Export: DwmModifyPreviousDxFrameDuration (ABI unverified)
// Export: DwmSetDxFrameDuration (ABI unverified)
// Export: DwmSetPresentParameters (ABI unverified)
// Export: DwmpEnableRedirection (ABI unverified)
// Export: DwmpSetColorizationColor (ABI unverified)
// Export: DwmpToggleFindMyMouse (ABI unverified)
// Export: DwmpUpdateWindowCapture (ABI unverified)
// Export: DwmEnableBlurBehindWindow (ABI unverified)
// Export: #ordinal185 (ABI unverified)
// Export: DwmpUpdateDisplayCaptureBorder (ABI unverified)
// Export: #ordinal140 (ABI unverified)
// Export: DwmpEndTransitionRequest (ABI unverified)
// Export: #ordinal148 (ABI unverified)
// Export: DwmpBeginTransitionRequestWithGUIDEx (ABI unverified)
// Export: #ordinal138 (ABI unverified)
// Export: DwmpBeginTransitionRequest (ABI unverified)
// Export: DwmRegisterThumbnail (ABI unverified)
// Export: #ordinal124 (ABI unverified)
// Export: DwmpRegisterThumbnail (ABI unverified)
// Export: DwmEnableMMCSS (ABI unverified)
// Export: #ordinal161 (ABI unverified)
// Export: DwmpSetImmersiveIconicNotifyWindow (ABI unverified)
// Export: #ordinal145 (ABI unverified)
// Export: DwmpBeginTransitionRequestWithGUID (ABI unverified)
// Export: #ordinal177 (ABI unverified)
// Export: DwmpStopDisplayCapture (ABI unverified)
// Export: DwmpUpdateProxyWindowForCapture (ABI unverified)
// Export: DwmpFreeSecurityDescriptor (ABI unverified)
// Export: #ordinal203 (ABI unverified)
// Export: DwmpBeginDisplayCapture (ABI unverified)
// Export: #ordinal202 (ABI unverified)
// Export: DwmpBeginWindowCapture (ABI unverified)
// Export: #ordinal180 (ABI unverified)
// Export: DwmpAddSharedProjectedShadowCaster (ABI unverified)
// Export: #ordinal164 (ABI unverified)
// Export: DwmpUpdateSharedMultiWindowVisual (ABI unverified)
// Export: #ordinal103 (ABI unverified)
// Export: #ordinal105 (ABI unverified)
// Export: DwmEnableComposition (ABI unverified)
// Export: DwmTetherTextContact (ABI unverified)
// Export: DwmpDxUpdateWindowSharedSurface (ABI unverified)
// Export: DwmpEnableDDASupport (ABI unverified)
// Export: DwmpRestartComposition (ABI unverified)
// Export: DwmpStartOrStopFlip3D (ABI unverified)
// Export: #ordinal109 (ABI unverified)
// Export: #ordinal110 (ABI unverified)
// Export: #ordinal112 (ABI unverified)
// Export: DwmAttachMilContent (ABI unverified)
// Export: DwmDetachMilContent (ABI unverified)
// Export: DwmGetGraphicsStreamClient (ABI unverified)
// Export: DwmGetGraphicsStreamTransformHint (ABI unverified)
// Export: DwmpCloseGraphicsStream (ABI unverified)
// Export: DwmpOpenGraphicsStream (ABI unverified)
// Export: DwmpSetGraphicsStreamTransformHint (ABI unverified)
// Export: #ordinal151 (ABI unverified)
// Export: DwmpBeginAnimationClock (ABI unverified)
// Export: #ordinal150 (ABI unverified)
// Export: DwmpCreateAnimationClock (ABI unverified)
// Export: #ordinal152 (ABI unverified)
// Export: DwmpEndAnimationClock (ABI unverified)
// Export: #ordinal153 (ABI unverified)
// Export: DwmpGetAnimationClockTime (ABI unverified)
// Export: #ordinal155 (ABI unverified)
// Export: DwmpGetAnimationClockToken (ABI unverified)
// Export: #ordinal178 (ABI unverified)
// Export: DwmpGetAnimationCommitHandle (ABI unverified)
// Export: #ordinal154 (ABI unverified)
// Export: DwmpSetAnimationClockTime (ABI unverified)
// Export: #ordinal107 (ABI unverified)
// Export: DwmpGetGlobalState (ABI unverified)
// Export: #ordinal192 (ABI unverified)
// Export: DwmpAddRemoveWindowToFilteredDisplayCapture (ABI unverified)
// Export: #ordinal174 (ABI unverified)
// Export: DwmpBeginDisplayCapture_Old (ABI unverified)
// Export: #ordinal204 (ABI unverified)
// Export: DwmpBeginFilteredDisplayCapture (ABI unverified)
// Export: #ordinal190 (ABI unverified)
// Export: DwmpBeginFilteredDisplayCapture_Old (ABI unverified)
// Export: #ordinal181 (ABI unverified)
// Export: DwmpBeginVirtualMonitorCapture (ABI unverified)
// Export: #ordinal173 (ABI unverified)
// Export: DwmpBeginWindowCapture_Old (ABI unverified)
// Export: #ordinal194 (ABI unverified)
// Export: DwmpBuildCaptureWindowVisualExclusionList (ABI unverified)
// Export: #ordinal189 (ABI unverified)
// Export: DwmpEnableModeChangeAnimation (ABI unverified)
// Export: #ordinal106 (ABI unverified)
// Export: DwmpIsCompositionCapable (ABI unverified)
// Export: #ordinal197 (ABI unverified)
// Export: DwmpIsWindowCapturable (ABI unverified)
// Export: #ordinal157 (ABI unverified)
// Export: DwmpRegisterSwapchainRenderTarget (ABI unverified)
// Export: #ordinal195 (ABI unverified)
// Export: DwmpRegisterWindowCloseHandle (ABI unverified)
// Export: #ordinal171 (ABI unverified)
// Export: DwmpSDRToHDRBoost (ABI unverified)
// Export: #ordinal200 (ABI unverified)
// Export: DwmpSetupDisplayCapture (ABI unverified)
// Export: #ordinal201 (ABI unverified)
// Export: DwmpSetupFilteredDisplayCapture (ABI unverified)
// Export: #ordinal199 (ABI unverified)
// Export: DwmpSetupWindowCapture (ABI unverified)
// Export: #ordinal191 (ABI unverified)
// Export: DwmpStopFilteredDisplayCapture (ABI unverified)
// Export: #ordinal182 (ABI unverified)
// Export: DwmpStopVirtualMonitorCapture (ABI unverified)
// Export: #ordinal176 (ABI unverified)
// Export: DwmpStopWindowCapture (ABI unverified)
// Export: #ordinal158 (ABI unverified)
// Export: DwmpUnregisterSwapchainRenderTarget (ABI unverified)
// Export: #ordinal196 (ABI unverified)
// Export: DwmpUnregisterWindowCloseHandle (ABI unverified)
// Export: #ordinal193 (ABI unverified)
// Export: DwmpUpdateFilteredDisplayCaptureBorder (ABI unverified)
// Export: #ordinal184 (ABI unverified)
// Export: DwmpUpdateWindowCaptureBorder (ABI unverified)
// Export: #ordinal167 (ABI unverified)
// Export: DwmpGetHmdStatus (ABI unverified)
// Export: #ordinal165 (ABI unverified)
// Export: DwmpSetHolographicExclusiveView (ABI unverified)
// Export: DwmRenderGesture (ABI unverified)
// Export: DwmTetherContact (ABI unverified)
// Export: DwmpRenderFlick (ABI unverified)
// Export: DwmGetTransportAttributes (ABI unverified)
// Export: DwmGetUnmetTabRequirements (ABI unverified)
// Export: #ordinal172 (ABI unverified)
// Export: DwmpGetTitleBarVisual (ABI unverified)
// Export: DwmSetIconicLivePreviewBitmap (ABI unverified)
// Export: #ordinal166 (ABI unverified)
// Export: DwmpSetChildRootVisual (ABI unverified)
// Export: #ordinal160 (ABI unverified)
// Export: DwmpSetImmersiveIconic (ABI unverified)
// Export: #ordinal142 (ABI unverified)
// Export: DwmpUpdateDesktopThumbnail (ABI unverified)
// Export: DwmTransitionOwnedWindow (ABI unverified)
// Export: #ordinal144 (ABI unverified)
// Export: DwmpTransitionBitmap (ABI unverified)
// Export: #ordinal188 (ABI unverified)
// Export: DwmpEnableWindowNotifications (ABI unverified)
// Export: #ordinal168 (ABI unverified)
// Export: DwmpResetColorizationParameters (ABI unverified)
// Export: DllCanUnloadNow (ABI unverified)
// Export: DllGetClassObject (ABI unverified)

#ifdef __cplusplus
} // extern "C"
#endif
#endif // DWMAPI_C_H
